### ISSUE TITLE
Catch unused interfaces?

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/tslint-rules#153]
This PR https://github.com/poetapp/node/pull/612 had an unused interface but the lint passed. 

Would be nice if the linter caught these.

**Comment by warrenv** [comment]
Which interface was removed in that PR @lautarodragan? I do not see any interfaces being removed in the diff.

**Comment by warrenv** [comment]
After researching this, I am unable to find any tslint rule/trick that will catch it.
