### ISSUE TITLE
Configure semantic release

### ISSUE THREAD

**Issue by wzalazar** [poetapp/tslint-rules#16]

**Comment by lautarodragan** [comment]
@geoffturk I'm tagging this as mainnet-beta since manual publishing is too problematic and configuring semantic release is probably a quick thing to do.

@wzalazar please confirm

**Comment by wzalazar** [comment]
@lautarodragan @geoffturk 

yes, this task is easy and fast

**Comment by geoffturk** [comment]
OK. Thanks for confirming.
