### ISSUE TITLE
Don't break function call parameters into separate lines when there's only 1 parameter

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/tslint-rules#4]
This:

```ts
await this.messaging.publishPoetTimestampsDownloaded(matchingPoetTimestamps)
```

is being changed into this:

```ts
+      await this.messaging.publishPoetTimestampsDownloaded(
+        matchingPoetTimestamps
+      )
```

by the current rules. I don't think this case makes the code more readable. 

But in cases with more parameters it does make the code more readable.

I suspect this is being done by prettier.

EDIT

I noticed this is happening for conditions too:

```ts
if (blockchainPoetMessage.version[i] !== this.configuration.poetVersion[i])
  return false
```

is being changed into 

```ts
if (
  blockchainPoetMessage.version[i] !== this.configuration.poetVersion[i]
)
  return false
```

**Comment by wzalazar** [comment]
@lautarodragan you consider this issue is following happen with the latest release launched? 

I have one doubts about this issue, What happens when the contract name of the method is greater than 120 characters?

**Comment by lautarodragan** [comment]
Hmm, I'd default to breaking the call into separate lines if it overflows (exceeds 120 chars) in that case.

Now that you mention it, I think this is no longer happening. Gotta confirm though

**Comment by geoffturk** [comment]
@lautarodragan Is this still an issue or did it get sorted in the linting changes?

**Comment by lautarodragan** [comment]
Sorry @geoffturk , never saw this message until now. No longer happening! Will close
