### ISSUE TITLE
no-any and no-unsafe-any

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/tslint-rules#42]
Can't think of any case in which we'd want to allow them. 

See https://palantir.github.io/tslint/rules/no-any/ and https://palantir.github.io/tslint/rules/no-unsafe-any/ for rationale.

**Comment by warrenv** [comment]
I think we should start with a warning rather than failing since it will be a large effort to correct all the code. The node repo alone has 638 warnings, 124 of them regarding the use of 'any'.
