### ISSUE TITLE
Issue with never prefixing interface names

### ISSUE THREAD

**Issue by kennylavender** [poetapp/tslint-rules#45]
This rule prevents me from using names that start with `I` for interfaces even if I am not using `I` as a prefix.

https://github.com/poetapp/tslint-rules/blob/master/poet-tslint.json#L13
```
      "interface-name": [true, "never-prefix"],
```

See https://github.com/poetapp/node/pull/215, I want to use the names `IPFSObject` and `IPFSConfiguration` for configuration, but I can't because tslint is throwing errors about I prefix's

```
ERROR: /home/kenny/projects/poet/node/src/Helpers/IPFSClient.ts[5, 11]: interface name must not have an "I" prefix
ERROR: /home/kenny/projects/poet/node/src/Helpers/IPFSClient.ts[18, 11]: interface name must not have an "I" prefix
```

**Comment by geoffturk** [comment]
Flagging this for @warrenv's attention. Please sync with @kennylavender to sort this if needed.
