### ISSUE TITLE
No Empty Return Blocks Rule Blocking Noop Function

### ISSUE THREAD

**Issue by jwicks31** [poetapp/tslint-rules#75]
We currently are unable to use the following format for no-op functions: `const noop = () => {}`

The initial discussion was held in [here](https://github.com/poetapp/frost-api/pull/257#discussion_r209715910)

Opening this issue up for further discussion on allowing empty return blocks.

**Comment by warrenv** [comment]
@lautarodragan @kennylavender @jwicks31, it looks like we have two options:

1. const noop = () => undefined
2. Disable the empty block linting rule.

Please respond here with your preferred solution.

**Comment by kennylavender** [comment]
I am good with both. I am not a fan of lint rules enforcing unimportant stuff like no empty blocks, but if its thought to be helpful then option 1 is fine.

**Comment by warrenv** [comment]
OK. Let's move forward with using `const noop = () => undefined` then.

**Comment by wzalazar** [comment]
@warrenv can you check if is the same with `const noop = R.always(undefined)`
